apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-app
      app.kubernetes.io/part-of: frontend-app
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-app
        app.kubernetes.io/part-of: frontend-app
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: frontend-app
        image: quay.io/isequeir/frontend-service:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/booktaxi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      volumes:
      - name: web-files
        configMap:
          name: www-files
      imagePullSecrets:
        - name: kmcdermo-pull-secret
